#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

printMessage "GENERATE DOCUMENTATION"
sbt docs/webStage

printMessage "PUBLISH ARTIFACTS"
sbt +publish
