#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

printMessage "PUBLISH RELEASE ARTIFACTS"
sbt +publishSigned
# TODO: remove before merge
sbt sonatypePrepare sonatypeBundleUpload
# TODO: Uncomment before merge
#sbt bintrayRelease
#sbt sonatypeBundleRelease