#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

# Lib for CI scripts

set -e
set -o pipefail

printMessage() {
  echo "[info]"
  echo "[info] ---- $1"
  echo "[info]"
}
