#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

printMessage "VALIDATE FILE HEADERS"
sbt +headerCheckAll

printMessage "VALIDATE SCALA CODE FORMATTING"
sbt scalafmtCheckAll scalafmtSbtCheck

printMessage "VALIDATE JAVA CODE FORMATTING"
sbt javafmtCheckAll
